import cv2
img1 = cv2.imread("sample1.png")
cv2.imshow("Red rose", img1)
cv2.imwrite("Rose.png",img1)
img2 = cv2.imread("sample2.jpg")
print(img2.shape)
print(img2.size)
print(img2.dtype)
grayImg = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
cv2.imwrite("GrayImage.jpg", grayImg)
cv2.imshow("Original", img2)
cv2.imshow("GrayImage", grayImg)
cv2.waitKey(0)
cv2.destroyAllWindows()
